### ISSUE TITLE
Print location of checkin

### ISSUE THREAD

**Issue by kriben** [kriben/untappdtoirc#2]
The venue of the checkin should be printed when nonempty.

**Comment by mdlayher** [comment]
I haven't implemented a `Venue` type yet in my library, but could probably whip up a basic one tonight, then tack on the added fields later.

**Comment by kriben** [comment]
@mdlayher Yes, I did not think of it when I was making the first implementation, but one of the guys in my irc channel asked for it immediately (since he was checking in from exotic San Francisco, I suspect).

**Comment by mdlayher** [comment]
@kriben I've implemented `Venue` and `VenueService` in my client.  You should be able to get the location using the `Venue.Location` struct's members.

**Comment by kriben** [comment]
@mdlayher I had a quick look, and the venue service itself looks good. But the venue is not parsed in the Checkin api. Is it okay that I add it there, or did you omit it "by design"? I can make some tests and a pull request tomorrow?

**Comment by mdlayher** [comment]
@kriben I just added it.  I ran into another "special case" in the API where it returns an empty array (`[]`) if no item was present.  You should be able to use it now, but do check `if checkin.Venue == nil` first, since a checkin without a Venue will report `nil` there.

**Comment by kriben** [comment]
@mdlayher Thanks! I have integrated it, and it seems to work OK.
